### ISSUE TITLE
Wrong Kafka bootstrap validation check

### ISSUE THREAD

**Issue by mykhailo-edcast** [ermadan/kafkalytic#15]
Couldn't add the bootstrap server

shami-1.kafka.us-west-1.amazonaws.com:1234 - works
shami-1.kafka.us-west-1.amazonaws.com:1234,shami-2.kafka.us-west-1.amazonaws.com:1234 - doesn't work
shami1.kafka.uswest1.amazonaws.com:1234,shami-2.kafka.us-west-1.amazonaws.com:1234 - works, looks like a small strange issue with regexp validation

**Comment by ermadan** [comment]
can you please try 0.9.7 version in alpha channel? issue should be fixed in this version

**Comment by ermadan** [comment]
fixed
