### ISSUE TITLE
Сolon escaping

### ISSUE THREAD

**Issue by StSerana** [ermadan/kafkalytic#29]
Hello!
I noticed that I can't get message header fully if header contains colon ":" at the beginning of publishing.
For Example: 
![image](https://user-images.githubusercontent.com/62513665/151306652-d53cf34d-b36b-4a26-a297-b3b5c865ad9b.png)
![image](https://user-images.githubusercontent.com/62513665/151306789-9fbace71-7182-4358-a89f-52a85140b160.png)

It would be great to have ability to escape characters.
Use kafkalytic v0.9.16

**Comment by ermadan** [comment]
hi, uploaded 0.10.2 in alpha channel with the fix, please check if it works for you
