### ISSUE TITLE
Bootstrap servers parsing error

### ISSUE THREAD

**Issue by RustamKuramshin** [ermadan/kafkalytic#3]
Как правило брокеры Kafka образуют кластер т.е. группу серверов. Сейчас в плагине в gui не правильно парсится строка с перечислением списка серверов через запятую. На скриншоте видно, что в таблице Host|Port неправильно парсится bootstrap servers.
![Выделение_020](https://user-images.githubusercontent.com/17687771/66899282-5a2d5800-f003-11e9-8ab7-b3164ebe5ce5.png)

**Comment by ermadan** [comment]
Рустам,
я сделал фикс и через несколько дней выложу в стабильную версию.
Можете ответить на пару вопросов касательно плагина:
1. Как вы храните connection properties в вашем приложении? Проперти файл или yaml? Будет ли удобно вместо ввода bootstrap сделать загрузку из файла?
2. Есть ли какие-то идеи как сделать удобнее работу плагина?

**Comment by RustamKuramshin** [comment]
Привет. 
1. Вроде бы в gui тулзах для kafka не используют загрузку из файла. Сам бэк, конечно имеет конфиг-файл, в котором кроме прочего есть настройки подключения к kafka. Мое мнение - в вашем плагине нужно вводить параметры подключения через gui, а не через файл.
2. Плагин добротный. На данный момент хотелось бы увидеть возможность просматривать конфигурацию кластера брокеров в самом плагине. Это удобно. Есть соответствующее api для этого на стороне kafka. 
Если возникнут какие-либо предложения по улучшению плагина, то напишу здесь в каком-нибудь issue.

**Comment by ermadan** [comment]
fixed in 0.9.2
