### ISSUE TITLE
Kafka delete records action can accept  "offset": -1 as value 

### ISSUE THREAD

**Issue by maks-pain** [ermadan/kafkalytic#43]
Kafka delete records action ("Remove messages before offset") can accept  "offset": -1 as a value so every partition could be cleared to the end.

But LONG_VALIDATOR does not allow this value.

https://github.com/ermadan/kafkalytic/blob/a44acbd441978a129a2d3b4d5af42fab04cb2319/src/main/kotlin/org/kafkalytic/plugin/SwingUtils.kt#L70

So UI can't accept "-1"

https://github.com/ermadan/kafkalytic/blob/a44acbd441978a129a2d3b4d5af42fab04cb2319/src/main/kotlin/org/kafkalytic/plugin/MainWindow.kt#L205C36-L205C36

**Comment by ermadan** [comment]
uploaded fix as 0.11.3 version into alpha channel, please check if it works for you. The version will be available for download tomorrow, after jetbrains security check.

**Comment by ermadan** [comment]
alpha channel https://plugins.jetbrains.com/plugin/11946-kafkalytic/versions/alpha

**Comment by maks-pain** [comment]
@ermadan thanks for fixing this.  Works perfectly!
