### ISSUE TITLE
Add custom name for connection

### ISSUE THREAD

**Issue by eugenone** [ermadan/kafkalytic#7]
Currently it is not possible to have multiple connections at the same address, because the name is determined from the address. However, it is often the case that different users have different views of topics and the connections must be created with separate keystores.

**Comment by ermadan** [comment]
hi, there is alpha version [0.9.1](https://plugins.jetbrains.com/plugin/11946-kafkalytic/update/78679)  that allows multiple connections to same address, i'd appreciate if you could check how it fits your requirements

**Comment by ermadan** [comment]
fixed in 0.9.2
